@url = http://localhost:8080/flexio/dayworkout

### Final All Workouts

GET {{url}} HTTP/1.1

### Find Workout by ID

GET {{url}}/1 HTTP/1.1

### Add Workout

POST {{url}}/add HTTP/1.1
Content-Type: application/json

{
    "day": 2024-04-04,
    "workoutName": "Abs"
}